"""remove video_data col

Revision ID: 1fa963a0c169
Revises: 3eaee781fd22
Create Date: 2024-03-19 18:35:12.301135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa963a0c169'
down_revision: Union[str, None] = '3eaee781fd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'video_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
