"""add watch_at column

Revision ID: cfa65299b7e5
Revises: ca851fafec63
Create Date: 2024-03-18 17:42:32.456995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa65299b7e5'
down_revision: Union[str, None] = 'ca851fafec63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_videos', sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_videos', 'watched_at')
    # ### end Alembic commands ###
