"""first build

Revision ID: 53e593c5ccfd
Revises: 
Create Date: 2024-03-24 00:33:47.916679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e593c5ccfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('uploader_username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('user_videos',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('username', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_videos')
    op.drop_table('videos')
    op.drop_table('users')
    # ### end Alembic commands ###
