"""add video uploader

Revision ID: 345ba56b00ff
Revises: 1fa963a0c169
Create Date: 2024-03-21 00:43:17.538709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345ba56b00ff'
down_revision: Union[str, None] = '1fa963a0c169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('uploader_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'videos', 'users', ['uploader_username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'uploader_username')
    # ### end Alembic commands ###
